language: csharp
solution: Sonda.sln
mono:
  - latest
  - 3.12.0
  - 3.10.0


before_install:
    - mkdir -p .nuget
    - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - mono .nuget/nuget.exe
install:
  - mono .nuget/nuget.exe
  - mono .nuget/nuget.exe restore Sonda.sln